Item10231: Add -x option to auto-reply to prompts
Also copy using -f option so read-only files don't break script.

git-svn-id: http://svn.foswiki.org/trunk@10752 0b4bb1d4-4e5a-0410-9cc4-b2b747904278

diff --git a/core/tools/foswiki-upgrade-check b/core/tools/foswiki-upgrade-check
--- a/core/tools/foswiki-upgrade-check
+++ b/core/tools/foswiki-upgrade-check
@@ -40,7 +40,7 @@ Options:
 		  file from DIR. Useful if DIR is a copy of your prod instance you
 		  upgraded previously to test things and do not want to repeat manual
 		  process and copy what you did there
-  -nom    no merge, for all conflicts keep your files
+  -x [ask old new merge] Conflict handling - default=ask.
 
 PS: do not forget to fix files permissions after this, for instance by a
 chown -R apache:apache ., chown -R www-data:www-data ., chmod -R a+rwX .
@@ -83,6 +83,7 @@ v1.6 2011-01-07 -r option (remove missing files).  Also prompt for optional merg
 v1.7 2011-02-16 Use jot if seq command does not exist (FreeBSD)
 V1.8 2011-02-19 exclude commonly tailored files,  Better handle files missing from old release
                 added -b option to backup files prior to modification
+                Deprecate -nom, and add -x option.  Copy files with -f option to override readonly
 '
 
 merge=merge_kdiff3
@@ -92,6 +93,7 @@ dolist=false
 listall=false
 verbose=false
 remove=false
+conflict=ask
 mfd=
 showdiff=
 seqcmd=true
@@ -136,7 +138,8 @@ while test "_${1#-}" != "_$1" -a "_${1//-/}" != "_";do case "$1" in
    -xxd) merge=merge_xxdiff;;
    -mld) merge=merge_meld;;
    -mfd) merge=merge_mfd; mfd=$2;shift;;
-   -nom) merge=merge_none;;
+   -nom) conflict=old;;
+   -x) conflict=$2;shift;;
    -s) showdiff=show_kdiff3;;
    -b) backup=true; B=$2;shift;;
    -a) dolist=true;;
@@ -160,6 +163,15 @@ case "$I" in /*) : ;; *) I="$PWD/$I";; esac
 case "$O" in /*) : ;; *) O="$PWD/$O";; esac
 case "$U" in /*) : ;; *) U="$PWD/$U";; esac
 
+autoresp=0;
+case $conflict in
+   ask) autoresp=0;;
+   merge) autoresp=1;;
+   old) autoresp=2;;
+   new) autoresp=3;;
+   *) echo "ERROR: incorrect option for -x: $conflict.  must be ask, old, new, merge."; exit 1;;
+esac
+
 if $backup; then
     case "$B" in /*) : ;; *) B="$PWD/$B";; esac
     if test ! -d $B; then
@@ -169,21 +181,23 @@ fi
 
 echo "
 
-Update files:  $doit
+Update files:  $doit  Conflicts: use $conflict
 Installation to be update:  $I
 Original release compared:  $O
 New release to be applied:  $U
 Optional backup directory:  $B
 
 "
+if $doit; then
 echo "Do you want to proceed?"
-select ans in "Yes" "No"
-do
-  case $ans in
-  "Yes" )  break;;
-  "No" ) exit 1; break;;
-  esac
-done
+    select ans in "Yes" "No"
+    do
+      case $ans in
+      "Yes" )  break;;
+      "No" ) exit 1; break;;
+      esac
+    done
+fi
 
 V () { if $verbose; then echo "$@"; fi; }
 doit () { if $doit; then "$@"; fi; }
@@ -192,7 +206,7 @@ dolist () { if ! $doit; then if $dolist; then echo $1; fi; fi; }
 bkit () { if $doit && $backup; then
     dir=$B/_bkup/$i; dir=${dir%/*}
     if test ! -d $dir; then mkdir -p $dir; fi
-    cp $I/$i $B/_bkup/$i
+    cp -f $I/$i $B/_bkup/$i
    fi
 }
 
@@ -209,7 +223,7 @@ show_kdiff3 () { kdiff3 $orig $I/$1 $U/$1; }
 merge_tkdiff () { tkdiff -a $orig -o $I/$1 $I/$1 $U/$1; }
 merge_xxdiff () { xxdiff --show-merged-pane -O -m -M $I/$1 $I/$1 $orig $U/$1; }
 merge_meld   () { meld $orig $I/$1 $U/$1; }
-merge_mfd    () { cp $mfd/$1 $I/$1; }
+merge_mfd    () { cp -f $mfd/$1 $I/$1; }
 merge_none   () { :; }
 
 is_binary () {
@@ -238,14 +252,14 @@ for element in $(doseq 0 $((${#file_list[@]} - 1))); do
             if cmp -s $O/$i $I/$i; then                     # Old same as installed
                V $i LOCALLY_SAME, DIST_CHANGED, COPY
                bkit $i
-               doit cp $U/$i $I/$i
+               doit cp -f $U/$i $I/$i
                dolist $i
             elif cmp -s $i $O/$i; then
                V $i LOCALLY_CHANGED, DIST_SAME. KEEP
             else                                           # Old file has changed
                 if test ! -e $O/$i; then
                     V $i NEW FILE, BUT DIFFERENT IN LOCAL AND UPGRADE
-                    echo "WARNING: New file $U/$i conflicts with existing file $I/$i "
+                    if $doit; then echo "WARNING: New file $U/$i conflicts with existing file $I/$i "; fi
                     orig=/dev/null
                 else
                     V $i CONFLICT, MERGE
@@ -255,19 +269,29 @@ for element in $(doseq 0 $((${#file_list[@]} - 1))); do
                     if is_binary "$i"; then
                         echo "WARNING: copied $U/$i over your $I/$i . Revert if wrong"
                         bkit $i
-                        doit cp $U/$i $I/$i
+                        doit cp -f $U/$i $I/$i
                         dolist $i
                     else
-                        echo "How do you want to handle conflict: $U/$i ?"
-                        select ans in "Merge files" "Keep original" "Use new file"
-                        do
-                            echo "Answer $ans "
-                            case $ans in
-                               "Merge files" ) echo "merge"; bkit $i;  doit $merge $i; break;;
-                               "Keep original" ) echo "keeping original"; break;;
-                               "Use new file" ) echo "using new"; bkit $i; doit cp $U/$i $I/$i; break;;
-                            esac
-                        done
+                        if  [ "$autoresp" = "0" ] ; then
+                            echo "How do you want to handle conflict: $U/$i ?"
+                            select ans in "Merge files" "Keep original" "Use new file"
+                            do
+                                echo "Answer $ans "
+                                case $ans in
+                                   "Merge files" ) echo "merge"; break;;
+                                   "Keep original" ) echo "keeping original"; break;;
+                                   "Use new file" ) echo "using new"; break;;
+                                esac
+                            done
+                        else
+                            ans=$autoresp
+                        fi
+                        case $ans in
+                           "1" ) echo "merge $i"; bkit $i;  doit $merge $i;;
+                           "2" ) echo "keeping original $i";;
+                           "3" ) echo "using new $i"; bkit $i; doit cp -f $U/$i $I/$i;;
+                        esac
+
                     fi
                 elif test -n "$showdiff"; then
                     if is_binary "$i"; then ls -l $orig $I/$1 $U/$1
@@ -284,7 +308,7 @@ for element in $(doseq 0 $((${#file_list[@]} - 1))); do
         if $doit; then
             dir=$I/$i; dir=${dir%/*}
             if test ! -d $dir; then mkdir -p $dir; fi
-            cp $U/$i $I/$i
+            cp -f $U/$i $I/$i
         fi
     fi
 done
